name	'base'
maintainer	'Sudharsan'
maintainer_email	'sudharsan@msn.com'
license	'Apache-2.0'
description	'Installs/Configures base'
long_description	IO.read(File.join(File.dirname(__FILE__), 'README.md'))
chef_version '13.6.4'
version 		'0.1.1'
supports		'redhat'
supports		'ubuntu'
issues_url 'https://github.com/sudharsananr/cookbooks/tree/master/base'
source_url 'https://github.com/sudharsananr/cookbooks/tree/master/base'
